" --------------------------------------------
" vim 环境设置
" --------------------------------------------
	set nu
	set ai
	set ts=4
	set	bg=dark

" --------------------------------------------
" ctags database path setting
" --------------------------------------------
	set tags=/Users/huyouliang/Documents/linux-2.6.39/tags

" --------------------------------------------
" cscope database path setting
" --------------------------------------------
	set csprg=/usr/local/bin/cscope
	set csto=0
	set	cst
	set	nocsverb
	cs add /Users/huyouliang/Documents/linux-2.6.39/cscope.out	/Users/huyouliang/Documents/linux-2.6.39
	set csverb

" --------------------------------------------
" Tap List setting
" --------------------------------------------
	filetype on
	nmap <F7> :TlistToggle<CR>
	let Tlist_Ctags_Cmd="/usr/local/bin/ctags"
	let	Tlist_Inc_Winwidth = 0
	let	Tlist_Exit_OnlyWindow = 0

	let	Tlist_Auto_Open = 0
	let	Tlist_Use_Right_Window = 1

" --------------------------------------------
" Source Explorer setting
" --------------------------------------------
	nmap <F8> :SrcExplToggle<CR>
	nmap <C-H>	<C-W>h
	nmap <C-J>	<C-W>j
	nmap <C-K>	<C-W>k
	nmap <C-L>	<C-w>l

	let g:SrcExpl_winHeight = 8
	let g:SrcExpl_refreshTime = 100
	let g:SrcExpl_jumpKey = "<ENTER>"
	let	g:SrcExpl_gobackKey = "<SPACE>"
	let	g:SrcExpl_isUpdateTags = 0

" --------------------------------------------
" NERD Tree Setting
" --------------------------------------------
	let	NERDTreeWinPos = "left"
	nmap <F9> :NERDTreeToggle<CR>


